In [2]:
import pandas as pd
import numpy as np

path = '/Users/nisitha/Development/Source/python/heroveird/assignment/28Mar_12Apr/Datasets/'
df_application = pd.read_csv(path + 'applications.csv', dtype={'Rejection_Reason': str})
df_branches = pd.read_csv(path + 'branches.csv')
df_customers = pd.read_csv(path + 'customers.csv')
df_defaults = pd.read_csv(path + 'defaults.csv')
df_loans = pd.read_csv(path + 'loans.csv')
df_transactions = pd.read_csv(path + 'transactions.csv')

## 1. Data Quality and Preparation
### > Validate and clean the datasets.
### > Check for missing values, duplicate entries, and inconsistent data.
### > Standardize date formats and remove irrelevant columns.
### > Handle outliers in numeric columns like Loan_Amount, Interest_Rate, andDefault_Amount.

In [3]:
# Store dataframes in a dictionary for easy iteration
dataframes = {
    "df_application": df_application,
    "df_branches": df_branches,
    "df_customers": df_customers,
    "df_defaults": df_defaults,
    "df_loans": df_loans,
    "df_transactions": df_transactions,
}
dataframes

{'df_application':       Application_ID  Loan_ID Customer_ID Application_Date Approval_Date  \
 0            A000001  L000001     C000001       2022-05-11    2020-10-02
 1            A000002  L000002     C000002       2022-03-18    2022-11-29
 2            A000003  L000003     C000003       2022-01-17    2023-07-01
 3            A000004  L000004     C000004       2019-03-09    2024-08-30
 4            A000005  L000005     C000005       2024-07-18    2020-03-18
 ...              ...      ...         ...              ...           ...
 82595        A082596      NaN     C016646       2021-08-19           NaN
 82596        A082597      NaN     C010571       2021-01-30           NaN
 82597        A082598      NaN     C006731       2023-04-17           NaN
 82598        A082599      NaN     C008140       2021-04-22           NaN
 82599        A082600      NaN     C060782       2023-05-28           NaN

           Loan_Purpose Source_Channel  Processing_Fee Approval_Status  \
 0             Business          Agent            6427        Approved
 1            Education         Online            8605        Approved
 2             Business         Online            1450        Approved
 3      Home Renovation          Agent            8171        Approved
 4            Education         Branch            4931        Approved
 ...                ...            ...             ...             ...
 82595        Education         Branch            9607        Rejected
 82596         Business         Branch            3281        Rejected
 82597         Personal         Branch            7207        Rejected
 82598         Personal         Online            8422        Rejected
 82599         Personal         Branch            7057        Rejected

            Rejection_Reason
 0                       NaN
 1                       NaN
 2                       NaN
 3                       NaN
 4                       NaN
 ...                     ...
 82595  Incomplete Documents
 82596  Incomplete Documents
 82597  Incomplete Documents
 82598   Insufficient Income
 82599  Incomplete Documents

 [82600 rows x 10 columns],
 'df_branches':    Branch_ID                   Branch_Name     Region  Total_Customers  \
 0       B001          Dhar, Kant and Madan       West             2891
 1       B002                    Shan Group       East             4459
 2       B003              Sachdev-Banerjee    Central             2504
 3       B004                  Kapadia-Brar       East             1542
 4       B005        Mangal, Kaur and Borde      South              945
 5       B006                   Doshi Group      North              525
 6       B007          Lad, Wali and Ramesh      North             4435
 7       B008                     Gala-Gara    Central             4647
 8       B009                    Vasa Group      North             3061
 9       B010                      Arya Ltd       West             4618
 10      B011                    Bhakta PLC      South             4108
 11      B012                      Kaul Inc       West             2408
 12      B013   Banik, Subramanian and Mane      North             4127
 13      B014           Bhatti, Rau and Sem      North             1706
 14      B015                    Apte Group      North             3737
 15      B016  Bhatnagar, Khalsa and Savant       East             4556
 16      B017                     Doshi LLC      North             3859
 17      B018    Sandhu, Magar and Sachdeva  Northeast             3609
 18      B019                    Bath-Bassi      North             4272
 19      B020              Contractor-Sodhi       West             1570
 20      B021               Viswanathan Ltd      South             3132
 21      B022  Bansal, Arya and Chakrabarti       East             4214
 22      B023       Wable, Butala and Kakar      South             4064
 23      B024                     Garde PLC    Central             1980
 24      B025                   Dhingra Ltd      North             1679
 25      B026                   Madan-Lanka      North             3567
 26      B027          Kapadia-Ramakrishnan       West             3715
 27      B028       Borah, Comar and Bhalla    Central             2705
 28      B029    Uppal, Sankaran and Thaker    Central             2423
 29      B030                   Kakar-Dutta       East             3069
 30      B031                       Sem Inc      South             2816
 31      B032             Mahajan-Zachariah  Northeast             1721
 32      B033          Saini, Iyer and Sani      South             3159
 33      B034         Raja, Ratta and Sathe    Central             4353
 34      B035  Malhotra, Boase and Malhotra    Central              927
 35      B036                     Kara-Bahl       East             1529
 36      B037                      Yogi Ltd      North             1760
 37      B038                      Loke Inc  Northeast              640
 38      B039  Zacharia, Srivastava and Sha      South              763
 39      B040       Dada, Chander and Bhatt      North             3174
 40      B041                      Dyal PLC  Northeast             2166
 41      B042                     Kar-Jaggi       West             2114
 42      B043                  Grover Group       East             3493
 43      B044                      Bawa Inc    Central             2621
 44      B045                  Solanki-Shah      South             3759
 45      B046                   Badal Group    Central             3056
 46      B047                 Chawla-Tandon       East             2017
 47      B048            Chawla-Subramanian    Central             4896
 48      B049        Khalsa, Mani and Banik      North             1284
 49      B050                     Sani-Kale      North             3075

     Total_Active_Loans  Delinquent_Loans  Loan_Disbursement_Amount  \
 0                  279                21                 341680882
 1                 1201               149                  96549019
 2                  122               168                 445787808
 3                 1422                96                 353934299
 4                 1613                87                 311637902
 5                  856                76                  10435197
 6                  468               200                  25191104
 7                  228               117                 240602090
 8                  236               106                 356643441
 9                 1810                49                 435407779
 10                1067                91                 149799582
 11                1714               104                 465469874
 12                1299               112                 255132776
 13                 439                67                 482327541
 14                 550                73                 139524261
 15                 577                81                  84694218
 16                 405               138                  75712441
 17                1815               154                 190472299
 18                 793                52                  13557923
 19                1751                89                 203940005
 20                 475               105                 150411759
 21                 946               114                 362728718
 22                1581               103                 269375830
 23                 744                42                 375279666
 24                1054               143                 125999612
 25                1677               139                 401253151
 26                 830                18                 299774333
 27                 551                70                 393550434
 28                1796               135                 234351532
 29                1849                18                  15022525
 30                 776                22                 180725549
 31                 251               171                  69415705
 32                1891               195                 190808551
 33                1151                98                 363032381
 34                 618               165                 449109596
 35                 949               106                 499562869
 36                1585               183                 420746720
 37                1393               113                  86826078
 38                 970               104                 136129255
 39                1933                10                 410883979
 40                1715                49                  96113763
 41                 477               160                 244555768
 42                 872               176                 447832443
 43                 256                69                  92708075
 44                 862               139                 306018078
 45                1648                43                 257206777
 46                1113                16                 146352191
 47                1601                87                 464419943
 48                 347               114                 136071324
 49                 323                91                 442594434

     Avg_Processing_Time  Relationship_Manager_Count
 0                     6                          29
 1                     8                          35
 2                    12                          48
 3                     9                          50
 4                    11                          10
 5                    15                           7
 6                     7                          30
 7                     7                          40
 8                    13                          32
 9                    10                          23
 10                   15                          18
 11                    3                          16
 12                    7                          34
 13                    7                          45
 14                   14                          32
 15                   11                           9
 16                   10                          19
 17                    2                          11
 18                   14                          17
 19                   13                          38
 20                    6                          13
 21                   15                          23
 22                    5                          16
 23                   11                          18
 24                    8                          41
 25                   14                          19
 26                    3                          11
 27                   12                          18
 28                    9                          46
 29                   11                          16
 30                   15                          11
 31                   12                          47
 32                    5                          10
 33                   10                          13
 34                   13                          29
 35                   11                           8
 36                   13                          22
 37                    6                          34
 38                   12                          40
 39                   10                          34
 40                    6                          25
 41                    2                          50
 42                   12                          48
 43                    6                          46
 44                    3                          23
 45                   11                          24
 46                    2                          30
 47                    4                           7
 48                   12                          23
 49                    1                          15  ,
 'df_customers':       Customer_ID       Full_Name  Contact_Number  \
 0         C000001    Shayak Kumar      1549750578
 1         C000002     Divij Ghosh      2121540709
 2         C000003   Rhea Bhargava    910320534937
 3         C000004   Indrans Walia      6566372162
 4         C000005     Saanvi Chad      9281095585
 ...           ...             ...             ...
 69995     C069996   Saksham Kohli      9648881025
 69996     C069997  Dharmajan Mall      2650655450
 69997     C069998      Eshani Ram      9210965566
 69998     C069999      Shaan Brar    911251433283
 69999     C070000    Amira Mander      4662335677

                                   Email  \
 0      saxenaindrans@gopal-krishnan.com
 1               ramanindranil@tella.com
 2                 bahlelakshi@mall.info
 3                    akadakia@yahoo.com
 4                   arhaan11@master.net
 ...                                 ...
 69995              tanyalalla@chand.com
 69996             elakshi28@hotmail.com
 69997       vedikaranganathan@gmail.com
 69998               ckurian@hotmail.com
 69999               surikabir@gmail.com

                                        Address  Age  Gender Marital_Status  \
 0      27/062\nSangha Nagar, Bongaigaon 736150   53    Male         Single
 1       H.No. 20, Edwin Circle\nKatihar 892167   62  Female         Single
 2           67/386\nComar Nagar, Chapra 137669   62   Other         Single
 3          88\nDhillon Ganj\nJamshedpur-816278   59  Female         Single
 4            011, Kunda Marg\nHyderabad-505161   56    Male         Single
 ...                                        ...  ...     ...            ...
 69995              57\nD’Alia\nMirzapur 764394   45    Male        Married
 69996    87/83, Rout Path\nNorth Dumdum-053905   56  Female         Single
 69997   H.No. 520\nThaman Marg\nPanipat-931124   49    Male         Single
 69998       14/928\nDin Zila\nNew Delhi-319692   57    Male       Divorced
 69999             35, Vala Marg\nOngole-557777   49    Male        Married

       Employment_Status  Annual_Income  Credit_Score     Region  \
 0            Unemployed         886810           433      North
 1         Self-Employed         396746           418       West
 2         Self-Employed        1118591           736  Northeast
 3              Salaried         524075           353    Central
 4         Self-Employed        1219355           735       West
 ...                 ...            ...           ...        ...
 69995     Self-Employed        1554577           576      South
 69996        Unemployed        1927952           824      South
 69997     Self-Employed         464958           629    Central
 69998          Salaried         812186           819  Northeast
 69999        Unemployed        1057211           760    Central

       Account_Tenure Relationship_Manager_ID
 0           12 Years                  RM0015
 1           10 Years                  RM0276
 2            9 Years                  RM0098
 3           11 Years                  RM0231
 4            1 Years                  RM0107
 ...              ...                     ...
 69995        2 Years                  RM0172
 69996        9 Years                  RM0382
 69997        3 Years                  RM0478
 69998        2 Years                  RM0295
 69999       12 Years                  RM0298

 [70000 rows x 14 columns],
 'df_defaults':      Default_ID  Loan_ID Customer_ID Default_Date  Default_Amount  \
 0       D000001  L007312     C007312   2022-07-20           94480
 1       D000002  L028234     C028234   2023-09-23           10912
 2       D000003  L008319     C008319   2024-08-04           73711
 3       D000004  L046668     C046668   2021-10-16           48955
 4       D000005  L082934     C082934   2024-10-07           56952
 ...         ...      ...         ...          ...             ...
 8995    D008996  L024498     C024498   2023-02-10           29136
 8996    D008997  L047391     C047391   2022-08-30            6612
 8997    D008998  L025077     C025077   2022-02-04           56304
 8998    D008999  L035371     C035371   2024-07-03           58524
 8999    D009000  L000676     C000676   2023-05-18           73274

          Default_Reason Recovery_Status  Recovery_Amount Legal_Action
 0              Job Loss            Full            30360          Yes
 1              Job Loss         Partial                0          Yes
 2                 Other             NaN             9866          Yes
 3                 Other             NaN                0          Yes
 4     Medical Emergency             NaN                0           No
 ...                 ...             ...              ...          ...
 8995              Other            Full            23424           No
 8996              Other            Full                0          Yes
 8997           Job Loss             NaN            38403          Yes
 8998   Business Failure         Partial            12863           No
 8999  Medical Emergency             NaN                0           No

 [9000 rows x 9 columns],
 'df_loans':        Loan_ID Customer_ID  Loan_Amount  Interest_Rate  Loan_Term  \
 0      L000001     C045929      4030468           8.45         24
 1      L000002     C038991      3498647          11.90         48
 2      L000003     C046662      4871438           9.74         24
 3      L000004     C040268       541515          13.55         24
 4      L000005     C067057       631036          10.10         36
 ...        ...         ...          ...            ...        ...
 89995  L089996     C062366      4932615          12.68         36
 89996  L089997     C010516      4493121          11.98         48
 89997  L089998     C052676      4107372          13.26         48
 89998  L089999     C068124       100576           8.69         12
 89999  L090000     C047600      4967379           7.24         60

       Disbursal_Date Repayment_Start_Date Repayment_End_Date Loan_Status  \
 0         2023-03-25           2023-04-25         2025-03-25      Active
 1         2023-10-23           2023-11-23         2027-10-23      Closed
 2         2024-07-30           2024-08-30         2026-07-30     Overdue
 3         2024-11-22           2024-12-22         2026-11-22      Active
 4         2024-03-30           2024-04-30         2027-03-30     Overdue
 ...              ...                  ...                ...         ...
 89995     2023-03-04           2023-04-04         2026-03-04      Closed
 89996     2022-11-02           2022-12-02         2026-11-02     Overdue
 89997     2024-11-26           2024-12-26         2028-11-26      Closed
 89998     2024-12-23           2025-01-23         2025-12-23      Active
 89999     2021-09-23           2021-10-23         2026-09-23      Active

        Overdue_Amount  EMI_Amount Collateral_Details
 0                   0       18668           Property
 1               44003       36012           Property
 2                   0       26347                NaN
 3                   0       16106                NaN
 4                   0       10127                NaN
 ...               ...         ...                ...
 89995               0       97438            Vehicle
 89996               0       99628            Vehicle
 89997           24135       42926                NaN
 89998            1262        3370                NaN
 89999           15916       50790                NaN

 [90000 rows x 12 columns],
 'df_transactions':        Transaction_ID  Loan_ID Customer_ID Transaction_Date Payment_Type  \
 0           T00000001  L005588     C050792       2021-04-30          EMI
 1           T00000002  L019942     C008919       2021-12-14      Penalty
 2           T00000003  L014848     C016745       2021-01-26          EMI
 3           T00000004  L041104     C039957       2021-02-18      Penalty
 4           T00000005  L002488     C056156       2024-12-07      Penalty

In [9]:

for name, df in dataframes.items():
    print(f"--- Validating DataFrame Started for: {name} ---")
    print("Shape:", df.shape)
    print("\nInfo:")
    df.info()
    print("\nMissing values:")
    print(df.isnull().sum())
    print("\nDuplicate rows:")
    print(df.duplicated().sum())
    
    primary_column = ''
    if name == "df_application":
        primary_column = 'Application_ID'
    elif name == "df_branches":
        primary_column = 'Branch_ID'
    elif name == "df_customers":
        primary_column = 'Customer_ID'
    elif name == "df_defaults":
        primary_column = 'Default_ID'
    elif name == "df_loans":
        primary_column = 'Loan_ID'
    elif name == "df_transactions":
        primary_column = 'Transaction_ID'

    print(f'\nUnique {primary_column} values:')
    display(df[primary_column].nunique())
    print('Total rows:', len(df))

    print(f"--- Validation Completed for: {name} ---\n\n")

--- Validating DataFrame Started for: df_application ---
Shape: (82600, 10)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82600 entries, 0 to 82599
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Application_ID    82600 non-null  object
 1   Loan_ID           70000 non-null  object
 2   Customer_ID       82600 non-null  object
 3   Application_Date  82600 non-null  object
 4   Approval_Date     70000 non-null  object
 5   Loan_Purpose      82600 non-null  object
 6   Source_Channel    82600 non-null  object
 7   Processing_Fee    82600 non-null  int64
 8   Approval_Status   82600 non-null  object
 9   Rejection_Reason  12600 non-null  object
dtypes: int64(1), object(9)
memory usage: 6.3+ MB

Missing values:
Application_ID          0
Loan_ID             12600
Customer_ID             0
Application_Date        0
Approval_Date       12600
Loan_Purpose            0
Source_Channel          0
Processing_Fee          0
Approval_Status         0
Rejection_Reason    70000
dtype: int64

Duplicate rows:
0

Unique Application_ID values:

82600

Total rows: 82600
--- Validation Completed for: df_application ---


--- Validating DataFrame Started for: df_branches ---
Shape: (50, 9)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Branch_ID                   50 non-null     object
 1   Branch_Name                 50 non-null     object
 2   Region                      50 non-null     object
 3   Total_Customers             50 non-null     int64
 4   Total_Active_Loans          50 non-null     int64
 5   Delinquent_Loans            50 non-null     int64
 6   Loan_Disbursement_Amount    50 non-null     int64
 7   Avg_Processing_Time         50 non-null     int64
 8   Relationship_Manager_Count  50 non-null     int64
dtypes: int64(6), object(3)
memory usage: 3.6+ KB

Missing values:
Branch_ID                     0
Branch_Name                   0
Region                        0
Total_Customers               0
Total_Active_Loans            0
Delinquent_Loans              0
Loan_Disbursement_Amount      0
Avg_Processing_Time           0
Relationship_Manager_Count    0
dtype: int64

Duplicate rows:
0

Unique Branch_ID values:

50

Total rows: 50
--- Validation Completed for: df_branches ---


--- Validating DataFrame Started for: df_customers ---
Shape: (70000, 14)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Customer_ID              70000 non-null  object
 1   Full_Name                70000 non-null  object
 2   Contact_Number           70000 non-null  int64
 3   Email                    70000 non-null  object
 4   Address                  70000 non-null  object
 5   Age                      70000 non-null  int64
 6   Gender                   70000 non-null  object
 7   Marital_Status           70000 non-null  object
 8   Employment_Status        70000 non-null  object
 9   Annual_Income            70000 non-null  int64
 10  Credit_Score             70000 non-null  int64
 11  Region                   70000 non-null  object
 12  Account_Tenure           70000 non-null  object
 13  Relationship_Manager_ID  70000 non-null  object
dtypes: int64(4), object(10)
memory usage: 7.5+ MB

Missing values:
Customer_ID                0
Full_Name                  0
Contact_Number             0
Email                      0
Address                    0
Age                        0
Gender                     0
Marital_Status             0
Employment_Status          0
Annual_Income              0
Credit_Score               0
Region                     0
Account_Tenure             0
Relationship_Manager_ID    0
dtype: int64

Duplicate rows:
0

Unique Customer_ID values:

70000

Total rows: 70000
--- Validation Completed for: df_customers ---


--- Validating DataFrame Started for: df_defaults ---
Shape: (9000, 9)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Default_ID       9000 non-null   object
 1   Loan_ID          9000 non-null   object
 2   Customer_ID      9000 non-null   object
 3   Default_Date     9000 non-null   object
 4   Default_Amount   9000 non-null   int64
 5   Default_Reason   9000 non-null   object
 6   Recovery_Status  6015 non-null   object
 7   Recovery_Amount  9000 non-null   int64
 8   Legal_Action     9000 non-null   object
dtypes: int64(2), object(7)
memory usage: 632.9+ KB

Missing values:
Default_ID            0
Loan_ID               0
Customer_ID           0
Default_Date          0
Default_Amount        0
Default_Reason        0
Recovery_Status    2985
Recovery_Amount       0
Legal_Action          0
dtype: int64

Duplicate rows:
0

Unique Default_ID values:

9000

Total rows: 9000
--- Validation Completed for: df_defaults ---


--- Validating DataFrame Started for: df_loans ---
Shape: (90000, 12)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Loan_ID               90000 non-null  object
 1   Customer_ID           90000 non-null  object
 2   Loan_Amount           90000 non-null  int64
 3   Interest_Rate         90000 non-null  float64
 4   Loan_Term             90000 non-null  int64
 5   Disbursal_Date        90000 non-null  object
 6   Repayment_Start_Date  90000 non-null  object
 7   Repayment_End_Date    90000 non-null  object
 8   Loan_Status           90000 non-null  object
 9   Overdue_Amount        90000 non-null  int64
 10  EMI_Amount            90000 non-null  int64
 11  Collateral_Details    59806 non-null  object
dtypes: float64(1), int64(4), object(7)
memory usage: 8.2+ MB

Missing values:
Loan_ID                     0
Customer_ID                 0
Loan_Amount                 0
Interest_Rate               0
Loan_Term                   0
Disbursal_Date              0
Repayment_Start_Date        0
Repayment_End_Date          0
Loan_Status                 0
Overdue_Amount              0
EMI_Amount                  0
Collateral_Details      30194
dtype: int64

Duplicate rows:
0

Unique Loan_ID values:

90000

Total rows: 90000
--- Validation Completed for: df_loans ---


--- Validating DataFrame Started for: df_transactions ---
Shape: (495000, 9)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495000 entries, 0 to 494999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Transaction_ID     495000 non-null  object
 1   Loan_ID            495000 non-null  object
 2   Customer_ID        495000 non-null  object
 3   Transaction_Date   495000 non-null  object
 4   Payment_Type       495000 non-null  object
 5   Amount             495000 non-null  int64
 6   Overdue_Fee        495000 non-null  int64
 7   Remaining_Balance  495000 non-null  int64
 8   Mode_of_Payment    495000 non-null  object
dtypes: int64(3), object(6)
memory usage: 34.0+ MB

Missing values:
Transaction_ID       0
Loan_ID              0
Customer_ID          0
Transaction_Date     0
Payment_Type         0
Amount               0
Overdue_Fee          0
Remaining_Balance    0
Mode_of_Payment      0
dtype: int64

Duplicate rows:
0

Unique Transaction_ID values:

495000

Total rows: 495000
--- Validation Completed for: df_transactions ---

In [10]:
# Standardize date formats for df_application
df_application['Application_Date'] = pd.to_datetime(df_application['Application_Date'])
df_application['Approval_Date'] = pd.to_datetime(df_application['Approval_Date'])

# Remove 'Rejection_Reason' column due to high missing values
df_application = df_application.drop(columns=['Rejection_Reason'])

print('--- df_application after cleaning ---')
display(df_application.head())
df_application.info()

--- df_application after cleaning ---

,Application_ID,Loan_ID,Customer_ID,Application_Date,Approval_Date,Loan_Purpose,Source_Channel,Processing_Fee,Approval_Status
0,A000001,L000001,C000001,2022-05-11,2020-10-02,Business,Agent,6427,Approved
1,A000002,L000002,C000002,2022-03-18,2022-11-29,Education,Online,8605,Approved
2,A000003,L000003,C000003,2022-01-17,2023-07-01,Business,Online,1450,Approved
3,A000004,L000004,C000004,2019-03-09,2024-08-30,Home Renovation,Agent,8171,Approved
4,A000005,L000005,C000005,2024-07-18,2020-03-18,Education,Branch,4931,Approved

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82600 entries, 0 to 82599
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Application_ID    82600 non-null  object
 1   Loan_ID           70000 non-null  object
 2   Customer_ID       82600 non-null  object
 3   Application_Date  82600 non-null  datetime64[ns]
 4   Approval_Date     70000 non-null  datetime64[ns]
 5   Loan_Purpose      82600 non-null  object
 6   Source_Channel    82600 non-null  object
 7   Processing_Fee    82600 non-null  int64
 8   Approval_Status   82600 non-null  object
dtypes: datetime64[ns](2), int64(1), object(6)
memory usage: 5.7+ MB

In [11]:
# Standardize date formats for df_defaults
df_defaults['Default_Date'] = pd.to_datetime(df_defaults['Default_Date'])

display(df_defaults.head())
df_defaults.info()

,Default_ID,Loan_ID,Customer_ID,Default_Date,Default_Amount,Default_Reason,Recovery_Status,Recovery_Amount,Legal_Action
0,D000001,L007312,C007312,2022-07-20,94480,Job Loss,Full,30360,Yes
1,D000002,L028234,C028234,2023-09-23,10912,Job Loss,Partial,0,Yes
2,D000003,L008319,C008319,2024-08-04,73711,Other,NaN,9866,Yes
3,D000004,L046668,C046668,2021-10-16,48955,Other,NaN,0,Yes
4,D000005,L082934,C082934,2024-10-07,56952,Medical Emergency,NaN,0,No

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Default_ID       9000 non-null   object
 1   Loan_ID          9000 non-null   object
 2   Customer_ID      9000 non-null   object
 3   Default_Date     9000 non-null   datetime64[ns]
 4   Default_Amount   9000 non-null   int64
 5   Default_Reason   9000 non-null   object
 6   Recovery_Status  6015 non-null   object
 7   Recovery_Amount  9000 non-null   int64
 8   Legal_Action     9000 non-null   object
dtypes: datetime64[ns](1), int64(2), object(6)
memory usage: 632.9+ KB

In [12]:
# Standardize date formats for df_loans
df_loans['Disbursal_Date'] = pd.to_datetime(df_loans['Disbursal_Date'])
df_loans['Repayment_Start_Date'] = pd.to_datetime(df_loans['Repayment_Start_Date'])
df_loans['Repayment_End_Date'] = pd.to_datetime(df_loans['Repayment_End_Date'])

# Remove 'Collateral_Details' column due to high missing values
df_loans = df_loans.drop(columns=['Collateral_Details'])

print('\n--- df_loans after cleaning ---')
display(df_loans.head())
df_loans.info()

--- df_loans after cleaning ---

,Loan_ID,Customer_ID,Loan_Amount,Interest_Rate,Loan_Term,Disbursal_Date,Repayment_Start_Date,Repayment_End_Date,Loan_Status,Overdue_Amount,EMI_Amount
0,L000001,C045929,4030468,8.45,24,2023-03-25,2023-04-25,2025-03-25,Active,0,18668
1,L000002,C038991,3498647,11.90,48,2023-10-23,2023-11-23,2027-10-23,Closed,44003,36012
2,L000003,C046662,4871438,9.74,24,2024-07-30,2024-08-30,2026-07-30,Overdue,0,26347
3,L000004,C040268,541515,13.55,24,2024-11-22,2024-12-22,2026-11-22,Active,0,16106
4,L000005,C067057,631036,10.10,36,2024-03-30,2024-04-30,2027-03-30,Overdue,0,10127

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Loan_ID               90000 non-null  object
 1   Customer_ID           90000 non-null  object
 2   Loan_Amount           90000 non-null  int64
 3   Interest_Rate         90000 non-null  float64
 4   Loan_Term             90000 non-null  int64
 5   Disbursal_Date        90000 non-null  datetime64[ns]
 6   Repayment_Start_Date  90000 non-null  datetime64[ns]
 7   Repayment_End_Date    90000 non-null  datetime64[ns]
 8   Loan_Status           90000 non-null  object
 9   Overdue_Amount        90000 non-null  int64
 10  EMI_Amount            90000 non-null  int64
dtypes: datetime64[ns](3), float64(1), int64(4), object(3)
memory usage: 7.6+ MB

In [13]:
# Standardize date formats for df_transactions
df_transactions['Transaction_Date'] = pd.to_datetime(df_transactions['Transaction_Date'])

print('\n--- df_transactions after cleaning ---')
display(df_transactions.head())
df_transactions.info()

--- df_transactions after cleaning ---

,Transaction_ID,Loan_ID,Customer_ID,Transaction_Date,Payment_Type,Amount,Overdue_Fee,Remaining_Balance,Mode_of_Payment
0,T00000001,L005588,C050792,2021-04-30,EMI,46099,1313,1513669,NEFT
1,T00000002,L019942,C008919,2021-12-14,Penalty,43648,4852,901455,UPI
2,T00000003,L014848,C016745,2021-01-26,EMI,1810,0,1922629,Cash
3,T00000004,L041104,C039957,2021-02-18,Penalty,8607,708,213581,UPI
4,T00000005,L002488,C056156,2024-12-07,Penalty,34720,0,411621,UPI

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495000 entries, 0 to 494999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Transaction_ID     495000 non-null  object
 1   Loan_ID            495000 non-null  object
 2   Customer_ID        495000 non-null  object
 3   Transaction_Date   495000 non-null  datetime64[ns]
 4   Payment_Type       495000 non-null  object
 5   Amount             495000 non-null  int64
 6   Overdue_Fee        495000 non-null  int64
 7   Remaining_Balance  495000 non-null  int64
 8   Mode_of_Payment    495000 non-null  object
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 34.0+ MB

In [14]:
# Function to handle outliers using IQR method
def handle_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Cap values outside the bounds
    df[column] = np.where(df[column] < lower_bound, lower_bound,
                          np.where(df[column] > upper_bound, upper_bound, df[column]))
    print(f"Outliers in '{column}' handled. New min: {df[column].min():.2f}, new max: {df[column].max():.2f}")

In [15]:
# Handle outliers in df_loans
print('--- Handling outliers in df_loans ---')
handle_outliers_iqr(df_loans, 'Loan_Amount')
handle_outliers_iqr(df_loans, 'Interest_Rate')

# Handle outliers in df_defaults
print('\n--- Handling outliers in df_defaults ---')
handle_outliers_iqr(df_defaults, 'Default_Amount')

print('\n--- Descriptive statistics after outlier handling ---')
print('df_loans:')
display(df_loans[['Loan_Amount', 'Interest_Rate']].describe())
print('\ndf_defaults:')
display(df_defaults[['Default_Amount']].describe())

--- Handling outliers in df_loans ---
Outliers in 'Loan_Amount' handled. New min: 50026.00, new max: 4999958.00
Outliers in 'Interest_Rate' handled. New min: 7.00, new max: 15.00

--- Handling outliers in df_defaults ---
Outliers in 'Default_Amount' handled. New min: 5010.00, new max: 99997.00

--- Descriptive statistics after outlier handling ---
df_loans:

        Loan_Amount  Interest_Rate
count  9.000000e+04   90000.000000
mean   2.516259e+06      11.005393
std    1.429289e+06       2.307139
min    5.002600e+04       7.000000
25%    1.275705e+06       9.000000
50%    2.510076e+06      11.010000
75%    3.751702e+06      13.010000
max    4.999958e+06      15.000000

df_defaults:

       Default_Amount
count     9000.000000
mean     52978.639667
std      27460.213066
min       5010.000000
25%      29486.500000
50%      53486.500000
75%      77012.000000
max      99997.000000